Progetto/Progetto/apps/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name='profile'),

    # Django auth
    path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path("signup/", views.SignUpView.as_view(), name="signup"),
]

Progetto/Progetto/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Progetto.apps.public.urls'), name='index'),
    path('accounts/', include('Progetto.apps.accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

Progetto/Progetto/apps/accounts/models.py
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    user_name = models.CharField(max_length=200, null=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    country_code = CountryField()
    mail = models.EmailField(max_length=254, null=True)

    def __str__(self):
        return self.user_name

Progetto/Progetto/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name= 'accounts/profile.html'

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"

Progetto/Progetto/views.py
from django.template import loader

Progetto/Progetto/templates/Coffees.html
{% extends 'base.html' %}
{% load static %}
{% url 'public:coffees' as coffees_url %}


{% block title %}Coffees{% endblock %}
<body>
    <main id="coffees">
        {% block content %}
        <section class="projects-section bg-light" id="projects">
            <div class="container px-2 px-lg-0">
                <!-- Featured Project Row-->
                <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="{% static 'theme/assets/img/bg-masthead.jpg' %}" alt="..." /></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <h4>
                            </h4>
                            <p class="text-black-50 mb-0">These are the coffees now available, look around and choose what you like!</p>
                        </div>
                    </div>
                </div>
                <!-- Project One Row-->
            {% for coffee in coffee_list %}
                <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4 class="text-white">{{coffee}}</h4>
                                    <p class="mb-0 text-white-50">{{coffee.description}}</p>
                                    <p class="mt-3"><a class="text-white-50" href='/coffees/{{coffee.id}}'>Learn more</a></p>
                                    <hr class="d-none d-lg-block mb-0 ms-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6"><img class="img-fluid" src={{coffee.coffee_image}} alt="..." /></div>
                </div>
            {% endfor %}    
            </div>
        </section>
        {% endblock %}
    </main>
</body>

Progetto/Progetto/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}

<body>
    <main id="about">
        {% block content %}
            <section class="about-section text-center" id="about">
                <div class="container px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-lg-8">
                            <h2 class="text-white mb-4">Made for newbies and pros alike</h2>
                            <p class="text-white-50">
                            This site has been created to help ease the learning curve of making coffee and to
                            help veterans in this space to test more without having to spend too much time doing the dirty work.
                            </p>
                        </div>
                    </div>
                </div>
            </section>
            <style>
                body{
                    background-image: url("{% static 'theme/assets/img/coffee-bar.jpg' %}");
                    background-position: center;
                    background-size: cover;
                }
            </style>
        {% endblock %}
    </main>
</body>

Progetto/Progetto/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

Progetto/Progetto/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}
{% with profile=user.profile %}
        <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-white mb-4">Welcome {{user.username}}!</h2>
                        {% if profile%}
                        <p class="text-white-50">
                            Email : {{profile.mail}}
                        </p>
                        <p class="text-white-50">
                            Country : {{profile.country_code}}
                        </p>
                        {% endif %}
                    </div>
                </div>
                <style>
                    body{
                        background-image: url("{% static 'theme/assets/img/coffee-bar.jpg' %}");
                        background-position: center;
                        background-size: cover;
                    }
                </style>
            </div>
        </section>
{% endwith%}
{% endblock %}

Progetto/Progetto/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Sign Up{% endblock %}

{% block content %}
<body>
    <main>
        <section class="signup-section" id="signup">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <p>
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Sign Up</button>
                            </form>
                        </p>
                    </div>
                </div>
            </div>
        </section>
    </main>
</body>
{% endblock %}

Progetto/Progetto/templates/base.html
<!-- tempplates/base.html-->
{% load static %}


<!DOCTYPE html>
<html>
<head>
    <meta charset="'utf-8">
    <title>{% block title %}Coffee House{% endblock %}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    {% include 'navbar.html' %}
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'theme/js/scripts.js' %}"></script>

</body>
</html>

Progetto/Progetto/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<section class="projects-section bg-light" id="projects">
    <div class="container px-2 px-lg-0">
        <!-- Featured Project Row-->
        <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
            <div class="">
                <div class="featured-text text-center text-lg-left">
                    <h4>
                    </h4>
                    <p class="text-black-50 mb-0">These are the coffees now available, look around and choose what you like!</p>
                </div>
            </div>
        </div>
{% endblock %}

Progetto/Progetto/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% url 'public:about' as about_url %}

{% block title %}Index{% endblock %}

<body>
    <main id="home">
        {% block content %}
        <!-- Masthead -->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase">Coffee House</h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">A free site to start your adventure in coffee</h2>
                        <a class="btn btn-primary" href='coffees'>Get Started</a>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
    </main>
</body>

Progetto/Progetto/templates/navbar.html
{% url 'public:contact' as contact_url %}
{% url 'public:about' as about_url %}
{% url 'public:index' as index_url %}
{% url 'public:coffees' as coffees_url %}
{% url 'accounts:profile' as profile_url %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href='{{ index_url }}'>Coffee House</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link {% if request.path == index_url %}active{% endif %}" href='{{ index_url }}'>Home</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == coffees_url %}active{% endif %}" href='{{ coffees_url }}'>Coffees</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == about_url %}active{% endif %}" href='{{ about_url }}'>About</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == contact_url %}active{% endif %}" href='{{ contact_url }}'>Contact</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link {% if request.path == profile_url %}active{% endif %}" href='{{ profile_url}}'>Profile</a></li>
                    <li class="nav-item"><a class="nav-link" href='{% url "accounts:logout" %}'>Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href='{% url "accounts:login" %}'>Login</a></li>
                    <li class="nav-item"><a class="nav-link" href='{% url "accounts:signup" %}'>Signup</a></li>
                {% endif%}
            </ul>
        </div>
    </div>
</nav>
<!--
<nav>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}<a href='{{ index_url }}'>Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href='{{ about_url}}'>About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contacts{% else %}<a href='{{ contact_url }}'>Contacts</a>{% endif %}</span>
    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
            <span> Hello {% if request.path == profile_url %}{{user.username}}{%else%}<a href="{{ profile_url}}">{{user.username}}</a>{% endif %}</span>
            <span><a href='{% url "accounts:logout" %}'>Logout</a></span>
        {% else %}
            <span><a href='{% url "accounts:login" %}'>Login</a></span>
        {% endif%}
    </span>
</nav> -->

Progetto/Progetto/templates/standard_coffee.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Coffees{% endblock %}
<body>
    <main id="coffees">
        {% block content %}
        <section class="projects-section bg-light" id="projects">
            <div class="container px-2 px-lg-0">
                <!-- Featured Project Row-->
                <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="{% static '/theme/assets/img/Coffee/' %}{{ coffee.imagename }}" alt="..." /></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <p class="text-black-50 mb-0">{{coffee.description}}</p>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <p class="text-black-50 mb-0">Producer: {{coffee.producer}}</p>
                        </div>
                        <div class="featured-text text-center text-lg-left">
                            <p class="text-black-50 mb-0">Origin: {{coffee.origin_area}}</p>
                        </div>
                        <div class="featured-text text-center text-lg-left">
                            <p class="text-black-50 mb-0">Tasting notes: {{coffee.tasting_notes}}</p>
                        </div>
                        <div class="featured-text text-center text-lg-left">
                            <p class="text-black-50 mb-0">Processes: {{coffee.processes}}</p>
                        </div>
                        <div class="featured-text text-center text-lg-left">
                            <p class="text-black-50 mb-0">Plant: {{coffee.plant_varieties}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock %}
    </main>
</body>